[package]
name = "flappy_dragon"
version = "0.1.0"
authors = ["Lewis Sneddon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.1"